services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: qsv-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: qsv-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
